{% set name = "vcrpy" %}
{% set version = "8.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46d64e77e8d95e5c76c7d9a94ff05d8b38b2ae4e1d4869eb0235024b6fcb5212

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - setuptools >=61.2
    - pip
    - wheel
  run:
    - python
    - pyyaml
    - wrapt

# E   ModuleNotFoundError: No module named 'pytest_httpbin'
{% set ignore_tests = " --ignore=tests/integration" %}
# E   fixture 'httpbin' not found
{% set deselect_tests = " --deselect=tests/unit/test_unittest.py::test_testcase_playback" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_stubs.py::TestVCRConnection::test_body_consumed_once_stream" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_stubs.py::TestVCRConnection::test_body_consumed_once_iterator" %}
# WIN path errors not found file with "/", neeeds "\\".
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_unittest.py::test_cassette_library_dir" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_unittest.py::test_vcr_kwargs_cassette_dir" %}  # [win]
test:
  source_files:
    - tests
  imports:
    - vcr
    - vcr.persisters
    - vcr.serializers
    - vcr.stubs
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - requests >=2.22.0

about:
  home: https://github.com/kevin1024/vcrpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatically mock your HTTP interactions to simplify and speed up testing
  description: This is a Python version of Ruby’s VCR library.
  dev_url: https://github.com/kevin1024/vcrpy
  doc_url: https://vcrpy.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
