travis:
  secure:
    BINSTAR_TOKEN: IhzTrEAFDxhSc+Lzb8bt1c7Xf6wFdMqZHng5sMxvKtz0C4mw2kgYCeCeThkH37cLeSLV67qZoBkARMzK7ecscIegynr7p083U04+TvN2/DspytuQQV8k/3bGchGXqi3Po0EpfU8vrkCRNV6rUbOqvY4voWtfI7DGzXhHP7cck6xDX3b2XWFt71Pb6imeKAJxHErnbaDkES8D+15+RoBfd5QwSfwRWTrPQmuy67L/fpdq4J1vqgelpOTGIfwun18O3heWyyADB7FTWmtObFHCFTs2OnM7mjZPGYGQ/KD8EVTu4CiBa38EpEUfwy6MQ9BSwf4HHPKitMySPyPRKwxPNWVVrhzzhQK58oGuex/88lv/LnLr90iwSfSF9v6PUJ21/RDVwtxzfkNcCxOG8KY29tYuHVEhqPELGS+Zc3dr6TxQ8A98r+XE/um7dllAoKZGCrSwnOy6hQdZXoDNt4FN5lTVa5YVZj4kQl+l42T367RgleMhGt9ed85ik0SI08+LkQuFgZUOQmWbh+oWPSshruXFG0uBAosNNXI/vZqHohfr9evzJXENiM0kOI2kR47jPA7+f5nEilGWMZDHwKdOfe5s9eXc2LeZezdVg8f2qyQHvttIO+NsbHSzJiCX/ylCcKIiaiJ+Ufzc0mlLTOiJN1Nc9ffxmr1EKw/3iuz4GwA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
